const fs=require('fs'),vm=require('vm'),path=require('path');const root=path.resolve(__dirname,'../public');
const sb={window:{},console:{log(){},info(){},warn(){},error(){}},Math,JSON,Date,Number,String,Array,Object,RegExp,Error,isFinite};vm.createContext(sb);for(const f of ['data.js','catalog-cards.js','balance-system.js','engagement-system.js','card-engine.js'])vm.runInContext(fs.readFileSync(root+'/'+f,'utf8'),sb,{filename:f});const W=sb.window;
function scan(v,path='root',bad=[]){if(v===undefined){bad.push(path+':undefined');return bad;}if(typeof v==='function'){bad.push(path+':function');return bad;}if(v===null||typeof v!=='object')return bad;if(v instanceof Date){bad.push(path+':Date');return bad;}if(Array.isArray(v))v.forEach((x,i)=>scan(x,path+'['+i+']',bad));else Object.keys(v).forEach(k=>scan(v[k],path+'.'+k,bad));return bad;}
function player(){return {name:'P',race:'Saiyan',health:100,maxHealth:100,shield:0,energy:6,dice:[6],diceCount:1,baseDamage:2,deck:[],hand:[],discard:[],endedTurn:false,specialization:'bruto'};}
function enemy(){return {id:'e1',name:'E',race:'Freezer',health:100,maxHealth:100,shield:0,pattern:[{tipo:'ataque',valor:2}],patternIndex:0,elite:false,boss:false,phases:[],statusResistances:[]};}
let p=player(),e=enemy(),combat={enemies:[e],round:1,players:{u:p},log:[],engagementObjective:null,sagaAct:1,teamSync:{value:0,lastPlayer:null,lastTag:null}};
W.Engagement.resetCombat(p);let ctx={player:p,playerId:'u',partner:null,allPlayers:combat.players,target:e,targets:[e],host:combat,round:1,paidCost:0,log(){},onKill(){},damageOthers(){}};W.CardEngine.onTurnStart(p,ctx);
let bad=scan(combat);console.log('initial bad',bad.slice(0,20),bad.length);
let count=0, badCards=[];for(const master of W.FULL_CARD_CATALOG){p=player();e=enemy();combat={enemies:[e],round:6,players:{u:p},log:[],engagementObjective:null,sagaAct:1,teamSync:{value:0,lastPlayer:null,lastTag:null}};W.Engagement.resetCombat(p);ctx={player:p,playerId:'u',partner:null,allPlayers:combat.players,target:e,targets:[e],host:combat,round:6,paidCost:master.costo,log(){},onKill(){},damageOthers(){}};try{W.CardEngine.resolve(JSON.parse(JSON.stringify(master)),ctx);const b=scan(combat);if(b.length)badCards.push([master.nombre,b.slice(0,5)]);count++;}catch(err){badCards.push([master.nombre,['THROW '+err.message]]);}}
console.log(JSON.stringify({count,badCards:badCards.slice(0,20),badCount:badCards.length},null,2));
