import {useEffect,useState} from 'react'; import {BrowserRouter,Link,Route,Routes} from 'react-router-dom'; import {observeAuth,login,register,guest,logout,friendlyAuthError} from '../firebase/authService'; import cards from '../cards/cards.json'; import {makeCombatant,type GameState} from '../core/GameState';import {draw,startRound,pass} from '../core/TurnManager'; import {playCard} from '../combat/CombatEngine'; import {remainingKi} from '../core/DiceSystem';import {generateMap} from '../roguelike/MapGenerator';import type {Card} from '../cards/cardTypes';
const deck=cards.slice(0,12) as unknown as Card[]; const boot=():GameState=>{const p=makeCombatant('p','Guerrero','SAIYAN',deck),e=makeCombatant('e','Centinela','FREEZER',deck,true);draw(p,4);draw(e,4);return startRound({round:1,combatants:[p,e],activeIndex:0,passed:[],log:[]},()=>.8)};
function Login(){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[err,setErr]=useState('');const go=async(f:()=>Promise<unknown>)=>{try{await f()}catch(e){setErr(friendlyAuthError(e))}};return <main className="login"><h1>ECOS DE KI</h1><p>Elige tu destino entre las estrellas.</p><input aria-label="Correo" placeholder="Correo" onChange={e=>setEmail(e.target.value)}/><input aria-label="Contraseña" type="password" placeholder="Contraseña" onChange={e=>setPassword(e.target.value)}/><button onClick={()=>go(()=>login(email,password))}>Entrar</button><button onClick={()=>go(()=>register(email,password))}>Crear cuenta</button><button onClick={()=>go(guest)}>Continuar como invitado</button>{err&&<p role="alert">{err}</p>}</main>}
function Menu(){return <main><h1>ECOS DE KI</h1><p>Un roguelike táctico de energía, dados y combate alterno.</p><nav><Link to="/run">Nueva expedición</Link><Link to="/deck">Mazo</Link><Link to="/multiplayer">Multijugador</Link></nav><button onClick={()=>logout()}>Cerrar sesión</button></main>}
function Run(){const map=generateMap();return <main><h2>Mapa de expedición</h2><div className="map">{map.map(n=><Link key={n.id} to="/battle" className={'node '+n.type}>{n.type}</Link>)}</div><Link to="/">Volver</Link></main>}
function Deck(){return <main><h2>Catálogo</h2><p>{cards.length} cartas normalizadas.</p><div className="cards">{cards.slice(0,24).map(c=><article className={'card '+c.cardType} key={c.id}><b>{c.cost} Ki</b><h3>{c.name}</h3><small>{c.cardType} {c.nature??''} {c.range??''}</small><p>{c.rulesText}</p></article>)}</div></main>}
function Battle(){const [state,setState]=useState(boot);const p=state.combatants[0],e=state.combatants[1];const act=(id:string)=>{const error=playCard(state,'p',id,'e');if(error)alert(error);setState({...state})};return <main className="battle"><header><h2>Ronda {state.round}</h2><div className="enemy"><b>{e.name}</b><progress value={e.hp} max={e.maxHp}/>{e.hp} HP</div></header><section className="arena"><div className="aura">⚡</div></section><section><h3>Dados: {p.dice.map((d,i)=><span className="die" key={i}>{d}</span>)} Ki {remainingKi(p)} / {p.dice.reduce((a,b)=>a+b,0)}</h3><p>Combo: {p.actionHistory.join(' → ')||'Preparando energía'}</p><p>{p.name} HP {p.hp}/{p.maxHp} · Awakening {p.awakeningMeter}%</p><div className="hand">{p.hand.map(c=><button className={'card '+c.cardType} onClick={()=>act(c.id)} key={c.id}><b>{c.cost}</b><strong>{c.name}</strong><small>{c.rulesText}</small></button>)}</div><button onClick={()=>{pass(state,'p');setState({...state})}}>Pasar ronda</button></section></main>}
function Multiplayer(){return <main><h2>Multijugador</h2><p>Crea una sala desde una cuenta autenticada para jugar cooperativo o PvP.</p><Link to="/">Volver</Link></main>}
function Shell(){const [ready,setReady]=useState(false),[user,setUser]=useState<unknown>(null);useEffect(()=>observeAuth(x=>{setUser(x);setReady(true)}),[]);if(!ready)return <main>Comprobando sesión…</main>;return <Routes><Route path="/login" element={<Login/>}/><Route path="*" element={user?<Routes><Route path="/" element={<Menu/>}/><Route path="/run" element={<Run/>}/><Route path="/deck" element={<Deck/>}/><Route path="/battle" element={<Battle/>}/><Route path="/multiplayer" element={<Multiplayer/>}/></Routes>:<Login/>}/></Routes>}; export default ()=> <BrowserRouter><Shell/></BrowserRouter>;
